apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: processcube-sample-app

resources:
  - https://github.com/5minds/ProcessCube.Deployment//base/?ref=main
  - namespace.yaml

patches:
  - target:
      group: networking.k8s.io
      kind: Ingress
      name: engine
    path: ./engine/ingress-patch.yml
  - target:
      group: networking.k8s.io
      kind: Ingress
      name: authority
    path: ./authority/ingress-patch.yml


configMapGenerator:
  - name: authority-config
    files:
      - ./authority/config.json