apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-token-secret
spec:
  secretStoreRef:
    kind: SecretStore
    name: controlling-plattform
  target:
    creationPolicy: Owner
  data:
    - secretKey: GIT_TOKEN
      remoteRef:
        key: github-token
        property: password
