apiVersion: batch/v1
kind: Job
metadata:
  name: artifactshipper
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        job: artifactshipper
    spec:
      containers:
        - name: artifactshipper
          image: 5minds/processcube_artifact_shipper:1.0.0-renovate-cd1e08-m46rx4vj
          imagePullPolicy: IfNotPresent
          env:
            - name: credentials__git__token
              valueFrom:
                secretKeyRef:
                  name: git-token-secret
                  key: GIT_TOKEN
          volumeMounts:
            - name: artifact-shipper-config
              mountPath: /config
            - name: tmpdir
              mountPath: /tmp
      volumes:
        - name: artifact-shipper-config
          configMap:
            name: artifact-shipper-config
        - name: tmpdir
          emptyDir:
            sizeLimit: 5000Mi
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
  backoffLimit: 4
