apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: processcube-sample-app

resources:
  - ../../base

patches:
  - target:
      group: networking.k8s.io
      kind: Ingress
      name: engine
    path: ./engine/ingress-patch.yml
  - target:
      group: apps
      kind: Deployment
      name: engine
    path: ./engine/deployment-patch.yml
  - target:
      group: networking.k8s.io
      kind: Ingress
      name: authority
    path: ./authority/ingress-patch.yml
  - target:
      group: apps
      kind: Deployment
      name: nodered
    path: ./lowcode/deployment-patch.yml
  - target:
      group: networking.k8s.io
      kind: Ingress
      name: nodered
    path: ./lowcode/ingress-patch.yml


configMapGenerator:
  - name: authority-config
    behavior: replace
    files:
      - ./authority/config.json