apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: processcube-demo-app

resources:
  - ../base/

patches:
  - target:
      group: networking.k8s.io
      kind: Ingress
      name: authority
    path: ./patches/authority/ingress-patch.yml
  - target:
      group: networking.k8s.io
      kind: Ingress
      name: engine
    path: ./patches/engine/ingress-patch.yml