apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: processcube-demo-app

resources:
  - git::https://github.com/5minds/ProcessCube.Deployment//base/?ref=main
  - namespace.yaml

patches:
  - target:
      group: networking.k8s.io
      kind: Ingress
      name: authority
    path: ./patches/authority/ingress-patch.yml
  - target:
      group: apps
      kind: Deployment
      name: engine
    path: ./patches/engine/deployment-patch.yml
  - target:
      group: networking.k8s.io
      kind: Ingress
      name: engine
    path: ./patches/engine/ingress-patch.yml
  - target:
      group: apps
      kind: Deployment
      name: postgres
    path: ./patches/engine/deployment-patch.yml